            <SearchableAutoSetting key="liveBurstStyle" />
            <SearchableAutoSetting key="timerColor" />
            <SearchableAutoSetting key="timerOpacity" />
+            <SearchableAutoSetting key="showWordSpeeds" />
+            <SearchableAutoSetting key="wordSpeedMode" />
+            <SearchableAutoSetting key="wordSpeedStep" wide />
+            <SearchableAutoSetting key="wordSpeedRequireFullWindow" />
            <SearchableAutoSetting key="highlightMode" wide />
            <SearchableAutoSetting key="typedEffect" />
