    "#e2b714",
    "#646669",
    "#2c2e31",
    "#d1d0c5",
    "#ca4754",
    "#7e2a33",
    "#ca4754",
    "#7e2a33",
  ] as CustomThemeColors,
  favThemes: [],
  showKeyTips: true,
  smoothCaret: "medium",
  codeUnindentOnBackspace: false,
  quickRestart: "off",
  punctuation: false,
  numbers: false,
  words: 50,
  time: 30,
  mode: "time",
  quoteLength: [1],
  language: "english",
  fontSize: 2,
  freedomMode: false,
  difficulty: "normal",
  blindMode: false,
  quickEnd: false,
  caretStyle: "default",
  paceCaretStyle: "default",
  flipTestColors: false,
  layout: "default",
  funbox: [],
  confidenceMode: "off",
  indicateTypos: "off",
  compositionDisplay: "replace",
  timerStyle: "mini",
  liveSpeedStyle: "off",
  liveAccStyle: "off",
  liveBurstStyle: "off",
+  // per-word speed labels (discussion #8294)
+  showWordSpeeds: false,
+  wordSpeedMode: "averaged",
+  wordSpeedStep: 5,
+  wordSpeedRequireFullWindow: true,
  colorfulMode: false,
  randomTheme: "off",
  timerColor: "main",
  timerOpacity: "1",
