  liveBurstStyle: {
    key: "liveBurstStyle",
    fa: { icon: "fa-tachometer-alt" },
    displayString: "live word burst style",
    changeRequiresRestart: false,
    group: "appearance",
    description:
      "Change the style of the live burst speed displayed during the test.",
  },
+  showWordSpeeds: {
+    key: "showWordSpeeds",
+    fa: { icon: "fa-tachometer-alt" },
+    displayString: "show per-word speeds",
+    changeRequiresRestart: false,
+    group: "appearance",
+    description: "Show small per-word speed labels above typed words.",
+  },
+  wordSpeedMode: {
+    key: "wordSpeedMode",
+    fa: { icon: "fa-tachometer-alt" },
+    displayString: "word speed mode",
+    changeRequiresRestart: false,
+    group: "appearance",
+    description: "Choose whether to show single-word WPM or averaged WPM over a window.",
+    optionsMetadata: {
+      off: { displayString: "off" },
+      single: { displayString: "single-word" },
+      averaged: { displayString: "averaged" },
+    },
+  },
+  wordSpeedStep: {
+    key: "wordSpeedStep",
+    fa: { icon: "fa-list-ol" },
+    displayString: "word speed step",
+    changeRequiresRestart: false,
+    group: "appearance",
+    description: "Show a label every N words.",
+  },
+  wordSpeedRequireFullWindow: {
+    key: "wordSpeedRequireFullWindow",
+    fa: { icon: "fa-window-maximize" },
+    displayString: "require full window for averaged",
+    changeRequiresRestart: false,
+    group: "appearance",
+    description: "Only show averaged label after a full N-word window has been typed.",
+  },
